### ISSUE TITLE
shadow-build-example not work

### ISSUE THREAD

**Issue by pkvov** [thheller/shadow-build#12]
i follow the https://github.com/thheller/shadow-build-example
but no luck and get theses error 
bash-3.2$ lein cljs-dev
Exception in thread "main" java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.IPersistentMap, compiling:(/private/var/folders/mk/ngydbzbn71718_nrwbbktgn40000gq/T/form-init6925\
48042160999884.clj:1:141)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to clojure.lang.IPersistentMap
        at clojure.lang.RT.dissoc(RT.java:758)
        at clojure.core$dissoc.invoke(core.clj:1434)
        at clojure.core$dissoc.doInvoke(core.clj:1436)
        at clojure.lang.RestFn.invoke(RestFn.java:490)
        at shadow.cljs.api$build_dev.doInvoke(api.clj:120)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.Var.invoke(Var.java:379)
        at user$eval5$fn__7.invoke(form-init692548042160999884.clj:1)
        at user$eval5.invoke(form-init692548042160999884.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        ... 11 more

**Comment by thheller** [comment]
Which leiningen version (```lein version```) are you using? I think only 2.5+ supports the feature I'm using to configure the build.

If you cannot upgrade your ```lein``` version I can provide an example that does not require specific leiningen versions if you need it.

**Comment by pkvov** [comment]
thanks, after upgrade to the 2.5.1 fixed the problem
