### ISSUE TITLE
goog.isProvided_ always returns false in dev mode

### ISSUE THREAD

**Issue by sritchie** [thheller/shadow-build#16]
I was trying to figure out why none of my code was getting hot loaded, and tracked it down to this patch in Weasel:

https://github.com/tomjakubowski/weasel/pull/54/files?diff=split

When optimizations are off, Weasel patches `goog.isProvided_` to always return false, which prevents code from ever getting reloaded.

Looking closer, clojurescript tries to encourage this method:

https://github.com/clojure/clojurescript/blob/master/src/cljs/clojure/browser/repl.cljs#L122

This means that the isProvided_ check is ALWAYS going to fail in dev mode.

What do you think about removing that check?

**Comment by thheller** [comment]
Weasel does not use shadow-build as far as I know. REPL support is something I am thinking about but as of now I do not think shadow-build is compatible with any of it. Especially the new stuff.

Not quite sure how you are using weasel together with shadow-build?

**Comment by sritchie** [comment]
I'm not using it together, I'm just using in my project. The problem is that Weasel (or any cljs repl) loads a bootstrap function that patches over that isProvided_ function. So, if anyone decides to use a repl at the same time as shadow build, it'll hose shadow build. Does that make sense?

**Comment by thheller** [comment]
Basically yes, if you try to use REPL related stuff in code compiled by shadow-build it will break.

How does your setup look like? Do you have a namespace that requires ```clojure.browser.repl``` (or any of the weasel stuff) but then doesn't connect to anything? Or do you have a second process running that the REPL actually connects to?

shadow-build uses a different monkey-patch [1] to work around the same issue the brepl/bootstrap does. I don't quite agree with many of the choices made in CLJS recently but that should not prevent you from using either, will look into it.

[1] https://github.com/thheller/shadow-build/blob/master/src/cljs/shadow/cljs/live_reload.cljs#L66-L67

**Comment by sritchie** [comment]
We have this namespace handy:

```clj
(ns racehub.repl
  (:require [weasel.repl :as ws-repl]))

(defn repl-connect []
  (when-not (ws-repl/alive?)
    (ws-repl/connect "ws://localhost:9001" :verbose true)))
```

Then we inject this script in: `"racehub.repl.repl_connect();"`

It looks like the repl is working great.

**Comment by thheller** [comment]
So you do have another REPL process running that serves the actual REPL but use .js created by shadow-build when loading the app?

**Comment by sritchie** [comment]
yup, that's correct.

I start the server-side repl with piggieback. I believe the only interaction the repl needs to have with `shadow-build` is that the files loaded by shadow also load all of the code needed by the client side of the repl.

**Comment by thheller** [comment]
Hmm surprised that works actually.

Can you try ```master```? Just pushed [1] which should work around ```repl/bootstrap``` replacing the function.

[1] https://github.com/thheller/shadow-build/commit/685ef373106f6d1f014d57c9dcbe882620db7b1f

**Comment by sritchie** [comment]
I'm seeing this when I change a file:

```
Waiting for modified files ...
File modified: racehub/client/cover_slide.cljs -> src/cljs/racehub/client/cover_slide.cljs
Exception in thread "main" java.lang.AssertionError: Assert failed: (compiler-state? state), compiling:(/Users/sritchie/code/clojure/racehub.com/target/d2a8fe63519a8293a6ca5bec662d049990fdc318-init.clj:1:4)
	at clojure.lang.Compiler.load(Compiler.java:7196)
	at clojure.lang.Compiler.loadFile(Compiler.java:7140)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.AssertionError: Assert failed: (compiler-state? state)
	at shadow.cljs.build$inspect_resource.invoke(build.clj:221)
	at shadow.cljs.build$reset_resource.invoke(build.clj:1408)
	at shadow.cljs.build$reload_modified_files_BANG_$fn__23812.invoke(build.clj:1542)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__6225.invoke(protocols.clj:103)
	at clojure.core.protocols$fn__6187$G__6182__6196.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6206.invoke(protocols.clj:65)
	at clojure.core.protocols$fn__6161$G__6156__6174.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6449)
	at shadow.cljs.build$reload_modified_files_BANG_.invoke(build.clj:1527)
	at shadow.cljs.build$watch_and_repeat_BANG_.invoke(build.clj:1613)
	at shadow.cljs.api$build_dev.doInvoke(api.clj:128)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval19541.invoke(d2a8fe63519a8293a6ca5bec662d049990fdc318-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6757)
	at clojure.lang.Compiler.eval(Compiler.java:6747)
	at clojure.lang.Compiler.load(Compiler.java:7184)
	... 11 more
```

**Comment by thheller** [comment]
Ah damn, should have done all that stuff in a branch. ;)

Should be fixed now.

**Comment by thheller** [comment]
Closing this as well. shadow-devtools pretty much addresses all of it, weasel no longer required.
