### ISSUE TITLE
valid-resource? fails on deps.cljs

### ISSUE THREAD

**Issue by sritchie** [thheller/shadow-build#18]
This function fails:

https://github.com/thheller/shadow-build/blob/883a9af081292dbe9bccc5475e2a8c98e5e7e0dc/src/clj/shadow/cljs/build.clj#L681

Because the deps files in cljs resources never get processed. Here's the error I get with the latest Om:

```clj
Exception in thread "main" clojure.lang.ExceptionInfo: not a valid resource {:js-name "deps.js", :type :cljs, :name "deps.cljs", :jar true, :source-path "/Users/sritchie/.m2/repository/cljsjs/react/0.12.2-5/react-0.12.2-5.jar", :last-modified 1422727277000, :url #<URL jar:file:/Users/sritchie/.m2/repository/cljsjs/react/0.12.2-5/react-0.12.2-5.jar!/deps.cljs>, :input #<Atom@2b67e627: "{:foreign-libs [{:file \"cljsjs/development/react.inc.js\", :file-min \"cljsjs/production/react.min.inc.js\", :provides [\"cljsjs.react\"]}], :externs [\"cljsjs/common/react.ext.js\"]}">}, compiling:(/Users/sritchie/code/clojure/racehub.com/target/9a6b5d006dceccf12c5a054b9c54bbcd67d9aded-init.clj:1:4)
	at clojure.lang.Compiler.load(Compiler.java:7196)
	at clojure.lang.Compiler.loadFile(Compiler.java:7140)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: not a valid resource {:js-name "deps.js", :type :cljs, :name "deps.cljs", :jar true, :source-path "/Users/sritchie/.m2/repository/cljsjs/react/0.12.2-5/react-0.12.2-5.jar", :last-modified 1422727277000, :url #<URL jar:file:/Users/sritchie/.m2/repository/cljsjs/react/0.12.2-5/react-0.12.2-5.jar!/deps.cljs>, :input #<Atom@2b67e627: "{:foreign-libs [{:file \"cljsjs/development/react.inc.js\", :file-min \"cljsjs/production/react.min.inc.js\", :provides [\"cljsjs.react\"]}], :externs [\"cljsjs/common/react.ext.js\"]}">}
	at clojure.core$ex_info.invoke(core.clj:4554)
	at shadow.cljs.build$merge_resource.invoke(build.clj:691)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__6225.invoke(protocols.clj:103)
	at clojure.core.protocols$fn__6187$G__6182__6196.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6206.invoke(protocols.clj:65)
	at clojure.core.protocols$fn__6161$G__6156__6174.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6449)
	at shadow.cljs.build$merge_resources.invoke(build.clj:698)
	at shadow.cljs.build$step_find_resources_in_jars$fn__23208.invoke(build.clj:708)
	at shadow.cljs.build$step_find_resources_in_jars.invoke(build.clj:706)
	at shadow.cljs.api$build_dev.doInvoke(api.clj:128)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.Var.invoke(Var.java:379)
	at user$eval19541.invoke(9a6b5d006dceccf12c5a054b9c54bbcd67d9aded-init.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6757)
	at clojure.lang.Compiler.eval(Compiler.java:6747)
	at clojure.lang.Compiler.load(Compiler.java:7184)
```

**Comment by sritchie** [comment]
Huh, looks like I get the same problem even if I guard against deps.cljs:

```
Caused by: clojure.lang.ExceptionInfo: not a valid resource {:jar true, :name "com/cognitect/transit/delimiters.js", :type :js, :last-modified 1417491298000, :source-path "/Users/sritchie/.m2/repository/com/cognitect/transit-js/0.8.723/transit-js-0.8.723.jar", :requires [], :js-name "com/cognitect/transit/delimiters.js", :url #<URL jar:file:/Users/sritchie/.m2/repository/com/cognitect/transit-js/0.8.723/transit-js-0.8.723.jar!/com/cognitect/transit/delimiters.js>, :provides #{com.cognitect.transit.delimiters}, :input #<Delay@1c290b82: :pending>}
```

**Comment by thheller** [comment]
Which version are you using? I recently changed a lot of this stuff and didn't quite finish yet. alpha10 is not ready yet, alpha9 should work though. Will look into it.

**Comment by sritchie** [comment]
This was all in alpha10. I backed down to alpha9 and this stuff works great. Thanks!

**Comment by thheller** [comment]
alpha10 should work now but it is still a work in progress so better stay at alpha9.
