### ISSUE TITLE
lein cljs throws an exception about `ns "constants-table" not available`

### ISSUE THREAD

**Issue by ocharles** [thheller/shadow-build#20]
```
ollie@nixos ~/w/d/f/frontend> nix-shell -I . --pure --command 'lein cljs'
warning: dumping very large path (> 256 MiB); this may run out of memory
Retrieving org/clojure/tools.nrepl/0.2.6/tools.nrepl-0.2.6.pom from central
Retrieving org/clojure/tools.nrepl/0.2.6/tools.nrepl-0.2.6.jar from central
-> Find cljs resources in jars
<- Find cljs resources in jars (248ms)
-> Find cljs resources in path: "src/cljs/"
<- Find cljs resources in path: "src/cljs/" (293ms)
-> Compiling Modules ...
Resolving deps for: fynder-sweatybetty.main
[:failed-to-compile #<ExceptionInfo clojure.lang.ExceptionInfo: ns "constants-table" not available {:ns constants-table}>]
clojure.lang.ExceptionInfo: ns "constants-table" not available {:ns constants-table}
	at clojure.core$ex_info.invoke(core.clj:4403)
	at shadow.cljs.build$get_deps_for_ns_STAR_.invoke(build.clj:408)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$get_deps_for_ns_STAR_.invoke(build.clj:417)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$get_deps_for_ns_STAR_.invoke(build.clj:417)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$get_deps_for_ns_STAR_.invoke(build.clj:417)
	at clojure.core.protocols$fn__6074.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$get_deps_for_ns_STAR_.invoke(build.clj:417)
	at shadow.cljs.build$get_deps_for_ns.invoke(build.clj:427)
	at shadow.cljs.build$resolve_main_deps.invoke(build.clj:805)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__6093.invoke(protocols.clj:98)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6076.invoke(protocols.clj:60)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$do_analyze_module.invoke(build.clj:998)
	at clojure.core.protocols$fn__6086.invoke(protocols.clj:143)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6080.invoke(protocols.clj:48)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at shadow.cljs.build$step_compile_modules$fn__6214.invoke(build.clj:1053)
	at shadow.cljs.build$step_compile_modules.invoke(build.clj:1050)
	at fynder.shadowbuild$dev$fn__6652.invoke(shadowbuild.clj:34)
	at fynder.shadowbuild$dev.doInvoke(shadowbuild.clj:32)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invoke(form-init3325986847244014903.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Waiting for modified files ...
```

`fynder.shadowbuild` is:

```clojure
(ns fynder.shadowbuild
  (:require [clojure.java.io :as io]
            [shadow.cljs.build :as cljs]))

(defn define-modules [state]
  (-> state
      (cljs/step-configure-module :cljs '[cljs.core clojure.walk clojure.string cljs.reader cljs.core.async] #{})
      (cljs/step-configure-module :test-support '[inflections.core no.en.core enfocus.bind fynder.winchan] #{:cljs})
      (cljs/step-configure-module :devel '[fynder.devel] #{:cljs})
      (cljs/step-configure-module :admin '[fynder-admin.main] #{:cljs})
      (cljs/step-configure-module :trainer '[fynder-trainer.main] #{:cljs})
      (cljs/step-configure-module :mobile '[fynder-mobile.main] #{:cljs})
      (cljs/step-configure-module :sweatybetty '[fynder-sweatybetty.main] #{:cljs})))

(defn dev
  "build the project, wait for file changes, repeat"
  [& args]
  (let [state (-> (cljs/init-state)
                  (cljs/enable-source-maps)
                  (assoc :optimizations :simple
                         :pretty-print false
                         :work-dir (io/file "target/cljs-work")
                         :public-dir (io/file "resources/dev")
                         :public-path "")
                  (cljs/step-find-resources-in-jars)
                  (cljs/step-find-resources "src/cljs/")
                  (cljs/step-finalize-config)
                  (cljs/step-compile-core)
                  (define-modules))]
    ;; compile, flush, reload, repeat
    (loop [state state]
      (let [new-state (try
                        (-> state
                            (cljs/step-compile-modules)
                            (cljs/flush-unoptimized)
                            (cljs/wait-and-reload!))
                        (catch Throwable t
                          (prn [:failed-to-compile t])
                          (.printStackTrace t)
                          (cljs/wait-and-reload! state)))]
        (recur new-state)))))

(defn prod
  "build the project, wait for file changes, repeat"
  [& args]
  (-> (cljs/init-state)
      (cljs/enable-emit-constants)
      (cljs/enable-source-maps)
      (assoc :optimizations :advanced
             :pretty-print false
             :work-dir (io/file "target/cljs-work")
             :public-dir (io/file "resources/prod")
             :externs ["externs/base32.js"
                       "externs/jquery.js"
                       "externs/react_addons.js"
                       "externs/fastclick.js"
                       "externs/socket.io.js"
                       "externs/moment.js"
                       "externs/papa.js"
                       "externs/markdown.js"
                       "externs/xss.js"
                       "externs/facebook.js"
                       "externs/colorpicker.js"
                       "externs/checkout.js"
                       "externs/countdown.js"
                       "externs/daterangepicker.js"])
      (cljs/step-find-resources-in-jars)
      (cljs/step-find-resources "src/cljs/")
      (cljs/step-finalize-config)
      (cljs/step-compile-core)
      (define-modules)
      (cljs/step-compile-modules)
      (cljs/closure-optimize)
      (cljs/flush-to-disk)
      (cljs/flush-modules-to-disk)))

(defn loader
  "build just the loader"
  [& args]
  (-> (cljs/init-state)
      (cljs/enable-emit-constants)
      (cljs/enable-source-maps)
      (assoc :optimizations :simple
             :pretty-print false
             :work-dir (io/file "target/cljs-work")
             :public-dir (io/file "resources/prod"))
      (cljs/step-find-resources-in-jars)
      (cljs/step-find-resources "src/cljs/")
      (cljs/step-finalize-config)
      (cljs/step-compile-core)
      (cljs/step-configure-module :fynder-loader '[fynder-loader.loader] #{})
      (cljs/step-compile-modules)
      (cljs/closure-optimize)
      (cljs/flush-to-disk)
      (cljs/flush-modules-to-disk)))
```

**Comment by ocharles** [comment]
Also, `project.clj` is:

```clojure
(defproject fynder-mobile "0.1.0"
  :dependencies [
                 ;; Clojure
                 [org.clojure/clojure "1.6.0"]
                 [io.fynder/core.async "0.1.0-SNAPSHOT"]
                 [org.clojure/core.match "0.3.0-alpha4"]
                 [environ "1.0.0"]
                 [compojure "1.3.2" :exclusions [ring/ring-core]]
                 [ring "1.3.2"]
                 [prismatic/schema "0.3.7"]
                 [enlive "1.1.5"]
                 [optimus "0.15.0"]
                 [optimus-less "0.2.0"]
                 [stasis "2.2.0" :exclusions [org.clojure/clojure]]
                 [clj-webdriver "0.6.1"]
                 [org.clojure/core.cache "0.6.4"]

                 ;; ClojureScript
                 [org.clojure/clojurescript "0.0-3123"]
                 [cljsjs/react-with-addons "0.12.2-7"]
                 [thheller/shadow-build "1.0.0-alpha10"]
                 [noencore "0.1.16"]
                 [org.omcljs/om "0.8.8" :exclusions [cljsjs/react]]
                 [sablono "0.3.4"]
                 [enfocus "2.1.0"]
                 [com.cemerick/url "0.1.1"]]
  :source-paths ["src/clj" "src/cljs"]
  :test-paths ["test/clj" "test/cljs"]
  :test-selectors {:default (complement :acceptance)
                   :acceptance :acceptance}
  :resource-paths ["resources"]
  :plugins [[lein-environ "0.5.0"]
            [lein-localrepo "0.5.3"]
            [com.cemerick/clojurescript.test "0.3.1"]
            [hiccup-bridge "1.0.1"]]
  :aliases {"cljs" ["run" "-m" "fynder.shadowbuild/dev"]
            "web" ["run" "-m" "fynder.webserver/web"]
            "acceptance" ["test" ":acceptance"]
            "export" ["run" "-m" "fynder.exporter"]
            "publish" ["with-profile" "prod" ["do"
                                              ["run" "-m" "fynder.shadowbuild/prod"]
                                              ["run" "-m" "fynder.shadowbuild/loader"]
                                              ["export"]]]}
  :local-repo ~(System/getenv "LOCAL_REPO") ; The deps repository can be overridden by a LOCAL_REPO variable.
  :repositories [["sonatype" {:url "http://oss.sonatype.org/content/repositories/releases"}]]
  :env {:google-maps-api-key "xxx"
        :stripe-api-key "xxx"
        :logging-enabled? true
        :analytics-enabled? true
        :widget-host "https://m.fynder.io"
        :api-server ""}
  :profiles {:dev {:repl-options {:init-ns fynder.webserver :timeout 120000}
                   :env {:logging-enabled? true
                         :analytics-enabled? false
                         :api-server "https://m-staging.fynder.io:443"}}})
```

**Comment by thheller** [comment]
Hey, I'm currently on the road and cannot and cannot look into this. Will check it out in a couple hours when I'm back home.

In the meanwhile you could probably try alpha11 which isn't really released yet but you can just clone the repo and run ```lein install```. Other than that everything looks about right. It should work if you remove ```enable-emit-constants``` but thats not ideal for production builds.

**Comment by ocharles** [comment]
No rush - I actually roll back to an older `project.clj` for local development as that also works. Product builds work fine with the above config though, so this isn't blocking me. Whenever you get a chance is fine :)

**Comment by ocharles** [comment]
Removing `enable-emit-constants` doesn't do it unfortunately. Haven't had a chance to grab alpha 11 just yet though.

**Comment by thheller** [comment]
I think it is related to the caching stuff I added recently in combination with multiple builds using the same directory.

Please try adding ```:cache-dir (io/file "target/cljs-cache")``` into the assoc on the ```dev``` and a different directory on the ```loader``` target. That might fix your troubles as I have no explanation why a dev build (which doesn't have ```emit-constants```) tries to load ``constants-table```.

The bigger issue might be that you are emitting the code in a different way than I intended.

It is intended that each build has its own directory since it is not just one file that is emitted in some cases (ie. source maps or modules). The idea is to use a directory so you can simply switch between dev and prod versions without adjusting anything on the server side but I don't quite understand what you are doing with the loader.

Suppose you are developing on the main javascript, you'd have ```lein cljs``` running in the background while you make your changes. Once you are ready you run ```lein run -m fynder.shadowbuild/prod``` and reload the page you were working on. It should now be using the production javascript without the server doing anything as long as the javascript is included via ```<script src="/assets/js/main/cljs.js"></script> + additional modules```.

I "updated" your build file to reflect that idea but it does make a lot of assumptions about how you access your javascript which might be totally different to what I do.

``` 
(ns fynder.shadowbuild
  (:require [clojure.java.io :as io]
            [shadow.cljs.build :as cljs]))

(defn define-modules [state]
  (-> state
      (cljs/step-configure-module :cljs '[cljs.core] #{})
      (cljs/step-configure-module :test-support '[inflections.core no.en.core enfocus.bind fynder.winchan] #{:cljs})
      (cljs/step-configure-module :devel '[fynder.devel] #{:cljs})
      (cljs/step-configure-module :admin '[fynder-admin.main] #{:cljs})
      (cljs/step-configure-module :trainer '[fynder-trainer.main] #{:cljs})
      (cljs/step-configure-module :mobile '[fynder-mobile.main] #{:cljs})
      (cljs/step-configure-module :sweatybetty '[fynder-sweatybetty.main] #{:cljs})))

(defn dev
  [& args]
  (-> (cljs/init-state)
      (cljs/enable-source-maps)
      (assoc :optimizations :none
             :pretty-print true
             :public-dir (io/file "resources/assets/js/main")
             :public-path "/assets/js/main")
      (cljs/step-find-resources-in-jars)
      (cljs/step-find-resources "src/cljs/")
      (cljs/step-finalize-config)
      (define-modules)
      (cljs/watch-and-repeat!
       (fn [state modified]
         (-> state
             (cljs/step-compile-modules)
             (cljs/flush-unoptimized))))))

(defn prod
  [& args]
  (-> (cljs/init-state)
      (cljs/enable-emit-constants)
      (cljs/enable-source-maps)
      (assoc :optimizations :advanced
             :pretty-print false
             :public-dir (io/file "resources/assets/js/main")
             :public-path (io/file "/assets/js/main")
             :externs ["externs/base32.js"
                       "externs/jquery.js"
                       "externs/react_addons.js"
                       "externs/fastclick.js"
                       "externs/socket.io.js"
                       "externs/moment.js"
                       "externs/papa.js"
                       "externs/markdown.js"
                       "externs/xss.js"
                       "externs/facebook.js"
                       "externs/colorpicker.js"
                       "externs/checkout.js"
                       "externs/countdown.js"
                       "externs/daterangepicker.js"])
      (cljs/step-find-resources-in-jars)
      (cljs/step-find-resources "src/cljs/")
      (cljs/step-finalize-config)
      (define-modules)
      (cljs/step-compile-modules)
      (cljs/closure-optimize)
      (cljs/flush-modules-to-disk)))

(defn loader
  "build just the loader"
  [& args]
  (-> (cljs/init-state)
      (cljs/enable-emit-constants)
      (cljs/enable-source-maps)
      (assoc :optimizations :simple
             :pretty-print false
             :public-dir (io/file "resources/assets/js/loader")
             :public-path (io/file "/assets/js/loader"))
      (cljs/step-find-resources-in-jars)
      (cljs/step-find-resources "src/cljs/")
      (cljs/step-finalize-config)
      (cljs/step-configure-module :fynder-loader '[fynder-loader.loader] #{})
      (cljs/step-compile-modules)
      (cljs/closure-optimize)
      (cljs/flush-to-disk)
      (cljs/flush-modules-to-disk)))
```

**Comment by ocharles** [comment]
Hey, thanks for fixing this up for me! Now that I "get" how shadow-build is meant to work this makes more sense and I'm back to having a working build/repl :) Happy to have this closed, if you think everything is resolved.

**Comment by thheller** [comment]
Glad to see it works now. I should really write some documentation about the finer points. :)
