### ISSUE TITLE
Problems with [org.clojure/clojurescript "0.0-3269"] and [org.clojure/clojure "1.7.0-beta2"]

### ISSUE THREAD

**Issue by ocharles** [thheller/shadow-build#21]
I may be jumping the gun a little here, as 1.7.0 isn't official out, but I get the following when I try and build using shadow-build:

```
-> Find cljs resources in jars
<- Find cljs resources in jars (1925ms)
-> Find cljs resources in path: "src/cljs/"
<- Find cljs resources in path: "src/cljs/" (228ms)
Exception in thread "main" clojure.lang.ExceptionInfo: Macro namespace: cljs.repl not found, required by #{"cljs/repl.cljs"} {:ns cljs.repl, :used-by #{"cljs/repl.cljs"}}, compiling:(/tmp/form-init1457659318691169198.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7249)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Macro namespace: cljs.repl not found, required by #{"cljs/repl.cljs"} {:ns cljs.repl, :used-by #{"cljs/repl.cljs"}}
	at clojure.core$ex_info.invoke(core.clj:4591)
	at shadow.cljs.build$discover_macros$fn__6160.invoke(build.clj:769)
	at clojure.core$map$fn__4550.invoke(core.clj:2622)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4125.invoke(core.clj:135)
	at clojure.core$map$fn__4550.invoke(core.clj:2614)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4125.invoke(core.clj:135)
	at clojure.core$map$fn__4550.invoke(core.clj:2614)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4109.invoke(core.clj:64)
	at clojure.core.protocols$fn__6517.invoke(protocols.clj:151)
	at clojure.core.protocols$fn__6474$G__6469__6483.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6500.invoke(protocols.clj:81)
	at clojure.core.protocols$fn__6448$G__6443__6461.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6515)
	at clojure.core$into.invoke(core.clj:6596)
	at shadow.cljs.build$discover_macros.invoke(build.clj:783)
	at shadow.cljs.build$step_finalize_config.invoke(build.clj:791)
	at fynder.shadowbuild$prod.doInvoke(shadowbuild.clj:58)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invoke(form-init1457659318691169198.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	... 11 more
```

Any ideas?

**Comment by ocharles** [comment]
I've been told on `#clojurescript` that this is because `cljs.repl` is now a `cljc` file (whatever that means :smile:) - not sure if that's helpful!

**Comment by thheller** [comment]
Yeah, I've been holding off on integrating the ```.cljc``` stuff until 1.7 was released. You can try the latest commit which will look for macro files with ```.clj``` and ```.cljc``` extensions.

**Comment by ocharles** [comment]
Perfect, that fixes that! Thank you :)
