### ISSUE TITLE
"nth not supported on this type: PersistentArrayMap" error when running tests

### ISSUE THREAD

**Issue by infracanophile** [thheller/shadow-build#27]
With one of my current cljc source files (a macro heavy file) I am getting this error trying to run tests.

It is thrown from here: https://github.com/clojure/clojurescript/blob/c72e9c52156b3b348aa66857830c2ed1f0179e8c/src/main/cljs/cljs/test.clj#L324

and the immediate cause is that the data structure returned from analyzer.api/ns-interns is not the normal ns-interns map but a set containing that map.

without this ns included in the build ns-interns results look normal, like:
```clojure
{test-simple-defrule
 {:protocol-inline nil,
  :meta
  {:file "demo/app_test.cljs",
   :line 100,
   :column 10,
   :end-line 100,
   :end-column 29},
  :name demo.app-test/test-simple-defrule,
  :variadic false,
  :file "demo/app_test.cljs",
  :end-column 29,
...etc.
```

and with that file included it is:
```clojure
#{{fact-session-test
   {:protocol-inline nil,
    :meta
    {:file "fact/clara_test.cljc",
     :line 19,
     :column 12,
     :end-line 19,
     :end-column 29},
    :name fact.clara-test/fact-session-test,
    :variadic false,
    :file "fact/clara_test.cljc",
    :end-column 29,
...etc
```

I wasn't able to track that any further, but have reproduced it in a fork of shadow-build-example here: https://github.com/infracanophile/shadow-build-example/tree/boot-shadow-test-issue

running a `boot cljs-test` will successfully run the tests compiling under boot-cljs and a `lein run -m build/test-all` will run the tests under shadow-build, throwing the exception in the title.

I should also mention that clara's unusual usage of `cljs.env/*compiler*` doesn't work under shadow-builds excellent incremental compilation/caching but I'm confident that is a unrelated (I could be wrong of course).

**Comment by thheller** [comment]
I'm not entirely sure what is happening here.

```clojure
(ns fact.clara-test
  (:require #?(:clj [clojure.test :as t]
               :cljs [cljs.test :as t])
            fact.clara
            [clara.rules :as clara]
            fact.clara-test-rules)
  #?(:cljs (:require-macros [cljs.test :as t]
                            fact.clara-test
                            fact.clara-test-rules)))
```

Why the extra `:require-macros` for `fact.clara-test` and `fact.clara-test-rules`? The files don't include any macros? I do not understand what `clara` is doing or how it is structured but if I remove those requires it compiles without error (and produces the same output as `boot` as far as I can tell).

`shadow-build` loads things a slightly different order from boot (or CLJS itself) which seems to confuse the compiler.

I'll try to look at `clara` to figure out what is going on. `cljs.env/*compiler*` should work as in normal `CLJS`. 

----


PS: `:require-macros` is only required to namespaces that do NOT have a self-require. `cljs.test` does have this which means you can `(:require [cljs.test :as t :refer (deftest is)])` or even skip the `:refer` and just use `t/deftest`. Just a little convenience.

This has been in `shadow-build` for a while now, but would break `boot`. So be careful before getting used to it.
http://dev.clojure.org/jira/browse/CLJS-948
http://dev.clojure.org/jira/browse/CLJS-1507

**Comment by thheller** [comment]
`clara` is downright scary. I have no idea what it is doing but it seems to be committing various sins.

**Comment by thheller** [comment]
When compiling after a `lein clean` the error is also different.

`Unable to resolve var: clara.macros/compile-alpha-nodes in this context, compiling:(fact/clara.cljc:55:21)`

For some reason the error is different when compiling incrementally which means it is somehow bypassing the various safeguards I have in place to prevent that from happening.

```
Exception in thread "main" clojure.lang.ExceptionInfo: compilation of "fact/clara.cljc" failed {}, compiling:(/private/var/folders/kq/vx6d7lyx6gz0n4jtrksfxmlw0000gn/T/form-init7113733734887220477.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: compilation of "fact/clara.cljc" failed {}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at shadow.cljs.build$par_compile_sources$fn__6671$fn__6672.invoke(build.clj:1436)
	at shadow.cljs.build$par_compile_sources$fn__6671.invoke(build.clj:1412)
	at clojure.core$with_redefs_fn.invoke(core.clj:7209)
	at shadow.cljs.build$par_compile_sources.invoke(build.clj:1411)
	at shadow.cljs.build$compile_modules$fn__6707.invoke(build.clj:1464)
	at shadow.cljs.build$compile_modules.invoke(build.clj:1457)
	at shadow.cljs.node$make_test_runner.invoke(node.clj:235)
	at shadow.cljs.node$make_test_runner.invoke(node.clj:231)
	at shadow.cljs.node$execute_all_tests_BANG_.invoke(node.clj:272)
	at build$test_all.invoke(build.clj:80)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval17.invoke(form-init7113733734887220477.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Caused by: clojure.lang.ExceptionInfo: failed to require macro-ns:fact.clara, it was required by:fact.clara {:ns-info {:require-order [clara.rules clara.rules.engine clara.rules.listener fact.namespaces], :use-macros {}, :excludes #{}, :name fact.clara, :op :ns, :env {:ns {:name cljs.user}, :context :statement, :locals {}, :fn-scope [], :js-globals {console {:name console}, location {:name location}, escape {:name escape}, screen {:name screen}, global {:name global}, process {:name process}, require {:name require}, alert {:name alert}, history {:name history}, window {:name window}, module {:name module}, exports {:name exports}, document {:name document}, navigator {:name navigator}, unescape {:name unescape}}, :line 1, :column 1}, :requires {clara.rules clara.rules, clara clara.rules, clara.rules.engine clara.rules.engine, eng clara.rules.engine, clara.rules.listener clara.rules.listener, l clara.rules.listener, fact.namespaces fact.namespaces}, :seen #{:require :require-macros}, :uses {}, :require-macros {fact.clara fact.clara}, :form (ns fact.clara (:require [clara.rules :as clara] [clara.rules.engine :as eng] [clara.rules.listener :as l] fact.namespaces) (:require-macros fact.clara))}}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at shadow.cljs.util$load_macros$fn__5975$fn__5982.invoke(util.clj:285)
	at shadow.cljs.util$load_macros$fn__5975.invoke(util.clj:282)
	at shadow.cljs.util$load_macros.invoke(util.clj:279)
	at shadow.cljs.build$post_analyze_ns.invoke(build.clj:545)
	at shadow.cljs.build$post_analyze.invoke(build.clj:554)
	at shadow.cljs.build$analyze.invoke(build.clj:598)
	at shadow.cljs.build$analyze.invoke(build.clj:578)
	at shadow.cljs.build$default_compile_cljs.invoke(build.clj:634)
	at clojure.core$partial$fn__4527.invoke(core.clj:2494)
	at shadow.cljs.build$do_compile_cljs_string$fn__6265.invoke(build.clj:627)
	at shadow.cljs.build$do_compile_cljs_string.invoke(build.clj:614)
	at shadow.cljs.build$compile_cljs_string$fn__6287.invoke(build.clj:668)
	at shadow.cljs.build$compile_cljs_string.invoke(build.clj:667)
	at shadow.cljs.build$do_compile_cljs_resource$fn__6301.invoke(build.clj:694)
	at shadow.cljs.build$do_compile_cljs_resource.invoke(build.clj:689)
	at shadow.cljs.build$maybe_compile_cljs.invoke(build.clj:829)
	at shadow.cljs.build$generate_output_for_source.invoke(build.clj:1349)
	at shadow.cljs.build$par_compile_one.invoke(build.clj:1393)
	at shadow.cljs.build$par_compile_sources$fn__6671$fn__6672$iter__6673__6677$fn__6678$fn__6679$fn__6680.invoke(build.clj:1422)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.core$bound_fn_STAR_$fn__4439.doInvoke(core.clj:1890)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to resolve var: clara.macros/compile-alpha-nodes in this context, compiling:(fact/clara.cljc:55:21)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3737)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6129)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler.eval(Compiler.java:6786)
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at shadow.cljs.util$load_macros$fn__5975$fn__5982.invoke(util.clj:283)
	... 33 more
Caused by: java.lang.RuntimeException: Unable to resolve var: clara.macros/compile-alpha-nodes in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:698)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
	... 78 more
```

**Comment by thheller** [comment]
Using the `cljs.env/*compiler*` directly like `fact.clara` is doing is also very unsafe since caching will almost always break it. When compiling incrementally you will be bypassing several stages and macro invocations might not happen causing the compiler env to look differently.

**Comment by thheller** [comment]
You may turn off caching by setting `:cache-level` to `:off` in `set-build-options`.

https://github.com/infracanophile/shadow-build-example/blob/boot-shadow-test-issue/dev/build.clj#L57
